# Generated by Django 4.0.3 on 2022-03-09 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorited',
            field=models.ManyToManyField(related_name='favorite_book', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='URL',
            field=models.URLField(max_length=500),
        ),
    ]
